### ISSUE TITLE
PYTHONPATH environment variable doesn't work when startline launched automatically

### ISSUE THREAD

**Issue by robw-uk** [mbradley612/HHSCStartLine#12]
PYTHONPATH does not contain a valid directory if the script is launched automatically i.e. as part of an xsession file.

2 Changes are requried

1) PYTHONPATH needs to be exported as an absolute path name
2) $PYTHONPATH needs to be prefixed to the call to start controllers.py and the location of startline.ini

e.g.

export PYTHONPATH=<source directory>
python $PYTHONPATH/controllers/controllers.py $PYTHONPATH/../startline.ini

**Comment by mbradley612** [comment]
Solution is to package all the python files in a zip, with a file called __main__. This file contains a function called main that gets executed if you pass the zip file to the Python interpreter. No more PYTHONPATH to worry about. Very neat.
Modified the startline structure to use this.
